# Copyright 2026 Alex313031

executable("langton_ants") {
  configs += [
    ":langton_ants_config",
    "src/logging:antlogger_config",
  ]
  precompiled_header = "src/framework.h"
  precompiled_source = "src/pch.cc"
  sources = [
    "src/ants.cc",
    "src/ants.h",
    "src/cpu.cc",
    "src/cpu.h",
    "src/langton_ants.rc",
    "src/framework.h",
    "src/globals.h",
    "src/main.cc",
    "src/main.h",
    "src/resource.h",
    "src/sound.cc",
    "src/sound.h",
    "src/ui_utils.cc",
    "src/ui_utils.h",
    "src/utils.cc",
    "src/utils.h",
    "src/version.h",
  ]
  deps = [
    "src/logging:antlogger",
  ]
}

config("langton_ants_config") {
  defines = []
  cflags = []
  include_dirs = [ "./src", ]
  cflags += [
    "-Wunused-function",
  ]
  libs = [
    "kernel32",
    "user32",
    "shell32",
    "comctl32",
    "comdlg32",
    "gdi32",
    "winmm",
  ]
}
