#ifndef LANGTON_ANTS_UTILS_H_
#define LANGTON_ANTS_UTILS_H_

#include "framework.h"

#include <logging.h>

// Color constants
#define RGB_BLACK   RGB(0, 0, 0)
#define RGB_WHITE   RGB(255, 255, 255)
#define RGB_GREY    RGB(128, 128, 128)
#define RGB_RED     RGB(255, 0, 0)
#define RGB_GREEN   RGB(0, 255, 0)
#define RGB_BLUE    RGB(0, 0, 255)
#define RGB_YELLOW  RGB(255, 255, 0)
#define RGB_CYAN    RGB(0, 255, 255)
#define RGB_MAGENTA RGB(255, 0, 255)

// Time constants
inline constexpr unsigned long kSlowSpeed  = 250UL;
inline constexpr unsigned long kMedSpeed   = 125UL;
inline constexpr unsigned long kHighSpeed  = 33UL;
inline constexpr unsigned long kHyperSpeed = 16UL;
inline constexpr unsigned long kRealTime   = 1UL;

extern unsigned long g_default_speed;

// Default desired ant canvas size (NOT the outer window size). wWinMain
// adds the OS chrome and the toolbar's measured height on top of these
// to compute the actual outer window size, so the user always gets a
// CW_WIDTH x CW_HEIGHT ant canvas at startup regardless of how tall the
// menu bar / toolbar end up being.
inline constexpr INT CW_WIDTH  = 640;
inline constexpr INT CW_HEIGHT = 640;

// Minimum desired ant canvas size. WM_GETMINMAXINFO converts these to
// outer-window minimums (chrome + g_toolbarHeight added) so the canvas
// never gets squeezed below this even when the toolbar wraps onto extra
// rows at narrow widths.
inline constexpr INT MINWIDTH  = 256;
inline constexpr INT MINHEIGHT = 256;

extern int g_toolbarHeight; // Height of the top toolbar in pixels; 0 if none. Ants "canvas" lives below it.

// Gets default settings from CHECKED state of menu items
void InitMenuDefaults(HWND hWnd);

// Gets the current side by side directory, regardless of where .exe is started from
const std::wstring GetExeDir();

// Save client area as a .BMP photo, capturing moment menu was clicked.
bool SaveClientBitmap(HWND hWnd);

// Test debug trap
void TestTrap();

// Helper functions for MessageBoxW
bool InfoBox(HWND hWnd, const std::wstring& title, const std::wstring& message);

bool WarnBox(HWND hWnd, const std::wstring& title, const std::wstring& message);

bool ErrorBox(HWND hWnd, const std::wstring& title, const std::wstring& message);

// Creates the app's top toolbar as a child of hParent. Call once from
// WM_CREATE. Stores the toolbar handle internally and measures the global
// g_toolbarHeight so the rest of the app can offset the ants area below it.
// Returns true on success; returns false if the toolbar window itself
// failed to create (callers can warn the user that the toolbar will be
// missing — the rest of the app still works via the menu bar).
bool CreateAppToolbar(HWND hParent, HINSTANCE hInst);

// Re-auto-sizes the toolbar to the parent's new width and re-measures its
// height into g_toolbarHeight. Call from WM_SIZE. No-op if the toolbar
// hasn't been created yet.
void LayoutToolbar(HWND hWnd);

// Swaps the IDM_PAUSED toolbar button's icon+label between "Pause" (simulation
// running) and "Resume" (simulation paused). Call after toggling g_paused.
void SetPauseButton(bool paused);

// Swaps the IDM_SOUND toolbar button's icon+label between "Music" (silent,
// click to start) and "Mute" (playing, click to stop). Call after ToggleSound.
void SetSoundButton(bool playing);

// Handles a TTN_GETDISPINFOW / TTN_NEEDTEXTW notification from the toolbar's
// tooltip control by supplying a descriptive string based on the hovered
// button's command ID (and, for state-toggling buttons, the current state).
// Call this first inside the parent's WM_NOTIFY and return early if it
// returns true. Returns false for any other notification code so the caller
// can continue dispatching.
bool HandleToolbarTooltips(NMHDR* pnmh);

// Pops up hMenu anchored just below the toolbar button identified by
// idCommand. Useful for WM_COMMAND handlers on TBSTYLE_DROPDOWN buttons
// where the user clicked the button body (not the arrow) and we want to
// show the same dropdown as TBN_DROPDOWN would. hOwner receives the
// WM_COMMAND messages generated by menu selections.
void PopupUnderToolbarButton(HWND hOwner, int idCommand, HMENU hMenu);

// Validates that the input from "Custom Seed" dialog is valid.
// Must be an unsigned integer, no spaces, decimals, or alphanumeric characters.
bool ValidateCustomSeed(LPCWSTR cSeed);

#endif // LANGTON_ANTS_UTILS_H_
